name: Run test

on: [push, pull_request]

jobs:
  dub-test:
    name: dub test
    strategy:
      matrix:
        os: [ubuntu-latest]
        dcompiler: [dmd-latest, ldc-latest]
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D Compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dcompiler }}
        
      - name: Run unit tests
        run: dub test

      - name: Run integration tests
        run: ./test.sh
        